name: Monitor WoW Updates

on:
  schedule:
    - cron: '0 11-23/2 * * *' # Runs every other hour during the day
  workflow_dispatch: # Allows manual triggers from GitHub UI

jobs:
  run-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 26
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Restore state.json
        uses: actions/cache/restore@v4
        with:
          path: state.json
          key: persistent-state-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            persistent-state-${{ runner.os }}-

      - name: Run watchdog
        run: pnpm start

      - name: Save state.json
        uses: actions/cache/save@v4
        if: always()
        with:
          path: state.json
          key: persistent-state-${{ runner.os }}-${{ github.run_id }}